### ISSUE TITLE
Puppeteer over a proxy

### ISSUE THREAD

**Issue by MaciekLeks** [vlocityinc/vlocity_build#400]
Does the tool support proxy for Puppeteer? If yes, what to do to make it works?

**Comment by MaciekLeks** [comment]
The simplest answer after digging in the code is NOT. Working behind the proxy and having puppeteer on the board makes the tool to crazy. 

Example log:
```
Sample error log part for Chromium without --proxy-server behind a proxy:

 Migrated 2333 items >> Deploying  
  Starting LWC Activation for Classic Card >> VlocityUILayout/b2bSampleAppCard  
  Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://productivity-leo-1124.cs101.my.salesforce.com/apex/vlocity_cmt__carddesignernew?id=a5t1X000000lgZNQAY&compile=true
    at navigate (/usr/local/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FrameManager.navigateFrame (/usr/local/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/local/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/usr/local/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:784:16)
    at async module.exports.VlocityUILayout.onDeployFinish (/usr/local/lib/node_modules/vlocity/lib/datapacktypes/vlocityuilayout.js:75:21)
    at async module.exports.VlocityCard.onDeployFinish (/usr/local/lib/node_modules/vlocity/lib/datapacktypes/vlocitycard.js:167:9)
    at async module.exports.DataPacksUtils.handleDataPackEvent (/usr/local/lib/node_modules/vlocity/lib/datapacksutils.js:2816:10)
    at async module.exports.DataPacksJob.deployJob (/usr/local/lib/node_modules/vlocity/lib/datapacksjob.js:2630:13)
    at async module.exports.DataPacksJob.doRunJob (/usr/local/lib/node_modules/vlocity/lib/datapacksjob.js:337:9)  
  Starting LWC Activation for Classic Card >> VlocityUILayout/b2bSampleAppCard  
```

**Comment by rutlabaga** [comment]
Fix merged to release in 1.14.14

**Comment by oxycash** [comment]
Is this issue resolved for you? I am still facing it even after specifying httpProxy in job yaml.

```
LWC Activation URL >> https://myorg.my.salesforce.com/apex/vlocity_cmt__OmniLwcCompile?id=a2XYZQ&activate=true  
  Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://myorg.my.salesforce.com/apex/vlocity_cmt__OmniLwcCompile?id=a2s260XYZAQ&activate=true
    at navigate (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:115:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FrameManager.navigateFrame (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:90:21)
    at async Frame.goto (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:417:16)
    at async Page.goto (/usr/lib/node_modules/vlocity/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:784:16)
    at async module.exports.OmniScript.compileOSLWC (/usr/lib/node_modules/vlocity/lib/datapacktypes/omniscript.js:231:13)
    at async module.exports.OmniScript.afterActivationSuccess (/usr/lib/node_modules/vlocity/lib/datapacktypes/omniscript.js:149:9)
    at async module.exports.DataPacksUtils.handleDataPackEvent (/usr/lib/node_modules/vlocity/lib/datapacksutils.js:2816:10)
    at async module.exports.DataPacksJob.activateAll (/usr/lib/node_modules/vlocity/lib/datapacksjob.js:2014:13)
    at async module.exports.DataPacksJob.deployPack (/usr/lib/node_modules/vlocity/lib/datapacksjob.js:2453:17)  
  LWC Activation Error >> OmniScript/btwsbuy2_landingPage_English - Error: net::ERR_TUNNEL_CONNECTION_FAILED at https://myorg.my.salesforce.com/apex/vlocity_cmt__OmniLwcCompile?id=a2s260XYZAQ&activate=true 
```

**Comment by MaciekLeks** [comment]
`httpProxy` no longer works for puppeteer.
Puppeteer's got own flag. See example code:
```bash
vlocity packDeploy -job some_job.yaml -sfdx.username $SOME_USER -puppeteerHttpProxy ${HTTPS_PROXY:-''}
```

**Comment by oxycash** [comment]
I figured that already but it is still not working. Then i found opening activation url was initially taking me to myorg.visualforce.con and redirecting to Salesforce.com domain, suspecting now our proxy is blocking it. Was it the case for you too? Because login url works for me but not activation url.

**Comment by MaciekLeks** [comment]
> 

Nop. My proxy ACL consists of this destinations at least:
```
.salesforce.com
.documentforce.com
.visualforce.com
.force.com
```
